#include "include/game_command.h"

#include "include/jni_helpers.h"

#include <cstddef>
#include <string>

namespace android_mod {
namespace {

struct OutfitSlotTable {
    int feature_num;
    const char *method;
    const char *const *values;
    std::size_t count;
};

constexpr const char *kBodyOutfitValues[] = {
    "CharSkyKid_Body_Ghost",
    "CharSkyKid_Body_Perfect",
    "CharSkyKid_Body_ClassicShortPants",
    "CharSkyKid_Body_ClassicDress",
    "CharSkyKid_Body_ClassicCivilian",
    "CharSkyKid_Body_ShortPants",
    "CharSkyKid_Body_LongPants",
    "CharSkyKid_Body_LongSkinnyPants",
    "CharSkyKid_Body_LongDancePants",
    "CharSkyKid_Body_MonkPants",
    "CharSkyKid_Body_LongMonkPants",
    "CharSkyKid_Body_WarriorPants",
    "CharSkyKid_Body_Museum",
    "CharSkyKid_Body_EvergreenRobe",
    "CharSkyKid_Body_AP04CozyPants",
    "CharSkyKid_Body_APMerchantPants_01",
    "CharSkyKid_Body_AP05JugglerPants_01",
    "CharSkyKid_Body_APDancerPants_01",
    "CharSkyKid_Body_APActorPants_01",
    "CharSkyKid_Body_AP07CargoPants_01",
    "CharSkyKid_Body_AP07Jumpsuits_01",
    "CharSkyKid_Body_AP08BaggyPants_01",
    "CharSkyKid_Body_AP09Uniform_01",
    "CharSkyKid_Body_AP09Yeti_01",
    "CharSkyKid_Body_AP10Overalls_01",
    "CharSkyKid_Body_AP11Ancestor_01",
    "CharSkyKid_Body_AP11Sword_01",
    "CharSkyKid_Body_AP11GreenPajama_01",
    "CharSkyKid_Body_AP12GradientTunic_01",
    "CharSkyKid_Body_AP12DarkTunic_01",
    "CharSkyKid_Body_AP12YellowTunic_01",
    "CharSkyKid_Body_AP12BlueTunic_01",
    "CharSkyKid_Body_AP13Tunic_01",
    "CharSkyKid_Body_AP14DancerSkirt_01",
    "CharSkyKid_Body_AP14ShadowPants_01",
    "CharSkyKid_Body_AP14JesterPants_01",
    "CharSkyKid_Body_AP15LightCreature_01",
    "CharSkyKid_Body_AP16WhiteCropTop",
    "CharSkyKid_Body_AP16SlateRunaway",
    "CharSkyKid_Body_AP16OrangeLove",
    "CharSkyKid_Body_AP16BlueSeed",
    "CharSkyKid_Body_AP16GreenCure",
    "CharSkyKid_Body_AP17RaggedTunic",
    "CharSkyKid_Body_AP17Injured",
    "CharSkyKid_Body_AP17Apron",
    "CharSkyKid_Body_AP18LightRobe",
    "CharSkyKid_Body_AP18DarkRobe",
    "CharSkyKid_Body_AP19MonkRobe",
    "CharSkyKid_Body_AP19CargoShorts",
    "CharSkyKid_Body_AP20Robe",
    "CharSkyKid_Body_AP21SilkRaiment",
    "CharSkyKid_Body_AP21LinenPants",
    "CharSkyKid_Body_AP21RoyalDress",
    "CharSkyKid_Body_AP21Coat",
    "CharSkyKid_Body_AP22Designer",
    "CharSkyKid_Body_AP23PianistBasic",
    "CharSkyKid_Body_AP23PianistSuit",
    "CharSkyKid_Body_AP23CellistBasic",
    "CharSkyKid_Body_AP26Gown",
    "CharSkyKid_Body_AP23CellistDress",
    "CharSkyKid_Body_AP24Classic",
    "CharSkyKid_Body_AP24Triangle",
    "CharSkyKid_Body_AP24Invisible",
    "CharSkyKid_Body_AP27Herder",
    "CharSkyKid_Body_AP24Bell",
    "CharSkyKid_Body_AP25BigPants",
    "CharSkyKid_Body_AP25Tunic",
    "CharSkyKid_Body_AP25Wrap",
    "CharSkyKid_Body_AP26Royal",
    "CharSkyKid_Body_AP26Lumberjack",
    "CharSkyKid_Body_AP27OldMan",
    "CharSkyKid_Body_AP27Guard",
    "CharSkyKid_Body_AP27Caretaker",
    "CharSkyKid_Body_AP28MantaWhisperer",
    "CharSkyKid_Body_AP28BirdTunic",
    "CharSkyKid_Body_AP28FurTrim",
    "CharSkyKid_Body_AP28JellyShorts",
    "CharSkyKid_Body_AP29ShortJacket",
    "CharSkyKid_Body_AP29Layered",
    "CharSkyKid_Body_AP29Pleated",
    "CharSkyKid_Body_FortuneMuralist",
    "CharSkyKid_Body_FortuneDragonRobe",
    "CharSkyKid_Body_Gardener",
    "CharSkyKid_Body_BloomSunflowerDress",
    "CharSkyKid_Body_BloomGreenTunic",
    "CharSkyKid_Body_OceanWaves",
    "CharSkyKid_Body_Rainbow_01",
    "CharSkyKid_Body_DarkRainbow",
    "CharSkyKid_Body_AP25RolledSleeve",
    "CharSkyKid_Body_BirthdayShirt_05",
    "CharSkyKid_Body_GreekRobe",
    "CharSkyKid_Body_FeastCoat",
    "CharSkyKid_Body_TreasurePants",
    "CharSkyKid_Body_SwimTrunks",
    "CharSkyKid_Body_SunlightDress",
    "CharSkyKid_Body_RibbonTieredDress",
    "CharSkyKid_Body_RibbonSkirt",
    "CharSkyKid_Body_MoonlightDress",
    "CharSkyKid_Body_FashionJeans",
    "CharSkyKid_Body_CrystalDress",
    "CharSkyKid_Body_CrystalSuit",
    "CharSkyKid_Body_Witch",
    "CharSkyKid_Body_Goth",
    "CharSkyKid_Body_Snowman",
    "CharSkyKid_Body_YellowPinafore",
    "CharSkyKid_Body_BandUniform",
    "CharSkyKid_Body_FortuneSnake",
    "CharSkyKid_Body_AnnivBeigeSuit",
    "CharSkyKid_Body_AnnivYellowGown",
    "CharSkyKid_Body_TriumphSkateOutfit",
    "CharSkyKid_Body_FortunePanelDress",
    "CharSkyKid_Body_TreasureDress",
    "NPC_CivilianMaleBody",
    "NPC_CivilianFemaleBody",
    "NPC_YoungFemaleBody",
    "NPC_LaborerMaleBody",
    "NPC_MerchantBody",
    "NPC_SkinnyIntellectualBody",
    "NPC_SkinnyIntellectualShawlDn",
    "NPC_KidLongPantsBody",
    "NPC_CivilianMaleBodyGhost",
    "CharSkyNPC_Body_MusicianRigGhost",
    "NPC_AP21SilkRaiment",
    "NPC_AP21RoyalDress",
    "NPC_AP21Coat",
    "NPC_AP21LinenPants",
    "NPC_AP22Designer",
    "NPC_AP23PianistBasic",
    "NPC_AP23PianistSuit",
    "NPC_AP23CellistBasic",
    "NPC_AP23CellistDress",
    "NPC_AP24Classic",
    "NPC_AP24Apron",
    "NPC_AP24TopHat",
    "NPC_AP24BellOnly",
    "NPC_AP24BellShoes",
    "NPC_AP24BellShoesCham",
    "NPC_AP24BellDress",
    "NPC_AP24BellFull",
    "NPC_AP24Stripes",
    "NPC_AP24Onion",
    "NPC_AP24Triangle",
    "NPC_AP24Ears",
    "NPC_AP25Tunic",
    "NPC_AP25Wrap",
    "NPC_AP25BigPants",
    "NPC_AP26Lumberjack",
    "NPC_AP26Gown",
    "NPC_AP26Royal",
    "NPC_AP27OldMan",
    "NPC_AP27Caretaker",
    "NPC_AP27Guard",
    "NPC_AP27GuardNoSword",
    "NPC_AP27Herder",
    "NPC_AP27NightElder",
    "NPC_AP28JellyShorts",
    "NPC_AP28BirdTunic",
    "NPC_AP28MantaWhisperer",
    "NPC_AP29PleatedCivilian",
    "NPC_AP29PleatedLaborer",
    "NPC_AP29ShortJacket",
    "NPC_AP29Layered",
    "CharSkyNPC_Body_Invisible",
    "CharSkyNPC_Body_MaleCivilian",
    "CharSkyNPC_Body_FemaleCivilian",
    "CharSkyNPC_Body_MerchantRig",
    "CharSkyNPC_Body_MusicianRig",
    "CharSkyNPC_Body_ActorRig",
    "CharSkyNPC_Body_DirectorRig",
    "CharSkyNPC_Body_DancerRig",
    "CharSkyNPC_Body_JugglerRig",
    "CharSkyNPC_Body_FatLabor",
    "CharSkyNPC_Body_FatLaborWave",
    "CharSkyNPC_Body_FatLaborStaff",
    "CharSkyNPC_Body_FatLaborChild",
    "CharSkyNPC_Body_StrongLabor",
    "CharSkyNPC_Body_StrongLaborHammer",
    "CharSkyNPC_Body_SkinnyIntellectual",
    "CharSkyNPC_Body_StrongKnight",
    "CharSkyNPC_Body_YoungFemaleRig",
    "CharSkyNPC_Body_RobedLadyRig",
    "CharSkyNPC_Body_FatLaborDress",
    "CharSkyNPC_Body_AP07CargoPants_01",
    "CharSkyNPC_Body_AP07Jumpsuits_01",
    "CharSkyNPC_Body_AP08Lion",
    "CharSkyNPC_Body_AP09Yeti_01",
    "CharSkyNPC_Body_AP10ClassClown",
    "CharSkyNPC_Body_AP11Prince",
    "CharSkyNPC_Body_AP11PrinceSpirit",
    "CharSkyNPC_Body_AP11Narcissist",
    "CharSkyNPC_Body_AP12GradientTunic_01",
    "CharSkyNPC_Body_AP12DarkTunic_01",
    "CharSkyNPC_Body_AP12YellowTunic_01",
    "CharSkyNPC_Body_AP12BlueTunic_01",
    "CharSkyNPC_Body_AP13Tunic_01",
    "CharSkyNPC_Body_AP14DancerSkirt_01",
    "CharSkyNPC_Body_AP14JesterPants_01",
    "CharSkyNPC_Body_AP14ShadowPants_01",
    "CharSkyNPC_Body_AP16BlueSeed",
    "CharSkyNPC_Body_AP16SlateRunaway",
    "CharSkyNPC_Body_AP16WhiteCropTop",
    "CharSkyNPC_Body_AP16OrangeLove",
    "CharSkyNPC_Body_AP16GreenCure",
    "CharSkyNPC_Body_AP17Apron",
    "CharSkyNPC_Body_AP17Injured",
    "CharSkyNPC_Body_AP18LightRobe",
    "CharSkyNPC_Body_AP19MonkRobe",
    "CharSkyNPC_Body_AP21King",
    "CharSkyNPC_Body_MoonlightDress",
    "CharSkyKid_Body_AP30RuffledShirt",
    "CharSkyKid_Body_AP30Romper",
    "CharSkyKid_Body_AP30WaistCoat",
    "CharSkyKid_Body_AP30PuffyDress",
    "NPC_AP30PuffyDress",
};
static_assert(sizeof(kBodyOutfitValues) / sizeof(kBodyOutfitValues[0]) == 214,
              "feature 1501 body table size mismatch");

constexpr const char *kMaskOutfitValues[] = {
    "CharSkyKid_Mask_Basic",
    "CharSkyKid_Mask_BasicQ",
    "CharSkyKid_Mask_BasicSleepy",
    "CharSkyKid_Mask_Bandana",
    "CharSkyKid_Mask_Smoke",
    "CharSkyKid_Mask_AP02Crab_01",
    "CharSkyKid_Mask_AP02Fox_01",
    "CharSkyKid_Mask_AP02Bird_01",
    "CharSkyKid_Mask_AP02Bull_01",
    "CharSkyKid_Mask_AP02Deer_01",
    "CharSkyKid_Mask_AP02Weasel_01",
    "CharSkyKid_Mask_AP03A",
    "CharSkyKid_Mask_AP03B",
    "CharSkyKid_Mask_AP03C",
    "CharSkyKid_Mask_AP03D",
    "CharSkyKid_Mask_AP03E",
    "CharSkyKid_Mask_AP03F",
    "CharSkyKid_Mask_AP03G",
    "CharSkyKid_Mask_AP04Child",
    "CharSkyKid_Mask_AP04Beard",
    "CharSkyKid_Mask_AP04Mustache",
    "CharSkyKid_Mask_AP04Adult",
    "CharSkyKid_Mask_APDefault",
    "CharSkyKid_Mask_APMerchant_01",
    "CharSkyKid_Mask_APActor_01",
    "CharSkyKid_Mask_APDirector_01",
    "CharSkyKid_Mask_AP05Musician_01",
    "CharSkyKid_Mask_AP06VeilA",
    "CharSkyKid_Mask_AP06VeilB",
    "CharSkyKid_Mask_AP06WizardBeard",
    "CharSkyKid_Mask_AP06Scarf",
    "CharSkyKid_Mask_AP07ThickBrows",
    "CharSkyKid_Mask_AP08Turtle",
    "CharSkyKid_Mask_AP08Spider",
    "CharSkyKid_Mask_AP08Bat",
    "CharSkyKid_Mask_AP08Lion",
    "CharSkyKid_Mask_AP08Wolf",
    "CharSkyKid_Mask_AP09Rabbit_01",
    "CharSkyKid_Mask_AP09Pigeon_01",
    "CharSkyKid_Mask_AP09Quail_01",
    "CharSkyKid_Mask_AP09Phoenix_01",
    "CharSkyKid_Mask_AP10QuestGiver_01",
    "CharSkyKid_Mask_AP10Eyepatch_01",
    "CharSkyKid_Mask_AP10Sticks_01",
    "CharSkyKid_Mask_AP10MaskA_01",
    "CharSkyKid_Mask_AP10MaskB_01",
    "CharSkyKid_Mask_AP10MaskC_01",
    "CharSkyKid_Mask_AP10MaskD_01",
    "CharSkyKid_Mask_AP11Frog_01",
    "CharSkyKid_Mask_AP13FullBeard_01",
    "CharSkyKid_Mask_AP13BraidedBeard_01",
    "CharSkyKid_Mask_AP13Cracked_01",
    "CharSkyKid_Mask_AP13Snorkel_01",
    "CharSkyKid_Mask_AP13SnorkelLite_01",
    "CharSkyKid_Mask_AP13ScarB_01",
    "CharSkyKid_Mask_AP14LongTufts_01",
    "CharSkyKid_Mask_AP14Surprised_01",
    "CharSkyKid_Mask_AP14Determined_01",
    "CharSkyKid_Mask_AP14Happy_01",
    "CharSkyKid_Mask_AP14Sad_01",
    "CharSkyKid_Mask_AP14Focused_01",
    "CharSkyKid_Mask_AP15DarkPlant_01",
    "CharSkyKid_Mask_AP16Fire",
    "CharSkyKid_Mask_AP16Water",
    "CharSkyKid_Mask_AP16Wind",
    "CharSkyKid_Mask_AP16Earth",
    "CharSkyKid_Mask_AP16CureForMe",
    "CharSkyKid_Mask_AP17PuffyBeard",
    "CharSkyKid_Mask_AP17Injured",
    "CharSkyKid_Mask_AP18Bear",
    "CharSkyKid_Mask_AP18Serow",
    "CharSkyKid_Mask_AP18Boar",
    "CharSkyKid_Mask_AP18Raccoon",
    "CharSkyKid_Mask_AP18Monkey",
    "CharSkyKid_Mask_AP19Scruffy",
    "CharSkyKid_Mask_AP19Blindfold",
    "CharSkyKid_Mask_AP21PaintMakeup",
    "CharSkyKid_Mask_AP21Eyebrows",
    "CharSkyKid_Mask_AP21Deer",
    "CharSkyKid_Mask_AP21Crescent",
    "CharSkyKid_Mask_AP23Seahorse",
    "CharSkyKid_Mask_AP25Gazelle",
    "CharSkyKid_Mask_AP26Peacock",
    "CharSkyKid_Mask_AP27FluffyBeard",
    "CharSkyKid_Mask_AP27ManateeMask",
    "CharSkyKid_Mask_AP27RulerMask",
    "CharSkyKid_Mask_AP27NightElder",
    "CharSkyKid_Mask_AP29RepairedA",
    "CharSkyKid_Mask_AP29RepairedB",
    "CharSkyKid_Mask_AP29RepairedC",
    "CharSkyKid_Mask_AP29RepairedD",
    "CharSkyKid_Mask_AP29RepairedE",
    "CharSkyKid_Mask_RedFace",
    "CharSkyKid_Mask_Ox",
    "CharSkyKid_Mask_Tiger_01",
    "CharSkyKid_Mask_FortuneRabbit",
    "CharSkyKid_Mask_Dragon",
    "CharSkyKid_Mask_FortuneSnake",
    "CharSkyKid_Mask_Rose",
    "CharSkyKid_Mask_Ocean",
    "CharSkyKid_Mask_OceanWaves",
    "CharSkyKid_Mask_RainbowDark",
    "CharSkyKid_Mask_ColorFacepaint",
    "CharSkyKid_Mask_RunwayMakeup",
    "CharSkyKid_Mask_MischiefCat",
    "CharSkyKid_Mask_Crabula",
    "CharSkyKid_Mask_MischiefBeak",
    "CharSkyKid_Mask_RibbonMask",
    "CharSkyKid_Mask_RosePetals",
    "CharSkyKid_Mask_TreasureEyePatch",
    "CharSkyKid_Mask_FortuneHorse",
    "CharSkyKid_Mask_SparrowCheeks",
    "CharSkyKid_Mask_Traveler_01",
    "CharSkyKid_Mask_Traveler_02",
    "CharSkyKid_Mask_None",
    "NPC_AP27GuardMask",
    "CharSkyKid_Mask_NPC",
    "CharSkyNPC_Mask_KnightHelmet",
    "CharSkyNPC_Mask_FatLaborMask",
    "CharSkyKid_Mask_AP30Puffin",
    "CharSkyKid_Mask_AP30Dodo",
};
static_assert(sizeof(kMaskOutfitValues) / sizeof(kMaskOutfitValues[0]) == 121,
              "feature 1502 mask table size mismatch");

constexpr const char *kFaceOutfitValues[] = {
    "CharSkyKid_Face_None",
    "CharSkyKid_Mask_ElderDawn",
    "CharSkyKid_Mask_ElderDay",
    "CharSkyKid_Mask_ElderRain",
    "CharSkyKid_Mask_ElderSunsetA",
    "CharSkyKid_Mask_ElderSunsetB",
    "CharSkyKid_Mask_ElderDusk",
    "CharSkyKid_Mask_ElderNight",
    "CharSkyKid_Mask_ElderDawn_02",
    "CharSkyKid_Mask_ElderDay_02",
    "CharSkyKid_Mask_ElderRain_02",
    "CharSkyKid_Mask_ElderSunsetA_02",
    "CharSkyKid_Mask_ElderSunsetB_02",
    "CharSkyKid_Mask_AP07Sunglasses",
    "CharSkyKid_Horn_AP19Glasses",
    "CharSkyKid_Horn_AP19Straw",
    "CharSkyKid_Horn_AP19SkullJaw",
    "CharSkyKid_Face_AP23Filigree",
    "CharSkyKid_Face_AP26BlueWings",
    "CharSkyKid_Face_AP26Plume",
    "CharSkyKid_Face_AP28AntlerHelm",
    "CharSkyKid_Mask_BlueSunglasses",
    "CharSkyKid_Horn_StarSunglasses",
    "CharSkyKid_Horn_FlameSunglasses",
    "CharSkyKid_Horn_HeartSunglasses",
    "CharSkyKid_Face_Monocle",
    "CharSkyKid_Horn_HeadCrab",
    "CharSkyKid_Face_CurseSticker",
    "CharSkyKid_Mask_YetiGoggles",
    "CharSkyKid_Face_Anniversary3DGlasses",
    "CharSkyKid_Face_AviatorMoth",
    "CharSkyKid_Face_PersonalityPurpleGlasses",
    "CharSkyKid_Face_PersonalityFLove",
    "CharSkyKid_Face_PersonalityTGear",
    "CharSkyKid_Horn_FortuneGlasses",
    "CharSkyKid_Horn_STARpin_sunglasses",
    "CharSkyKid_Face_AP27NightElder",
    "CharSkyKid_Face_AP28RoundGlasses",
};
static_assert(sizeof(kFaceOutfitValues) / sizeof(kFaceOutfitValues[0]) == 38,
              "feature 1503 face table size mismatch");

constexpr const char *kNeckOutfitValues[] = {
    "CharSkyKid_Neck_None",
    "CharSkyKid_Neck_AP02Pendant",
    "CharSkyKid_Neck_AP03Pendant",
    "CharSkyKid_Neck_AP04Pendant",
    "CharSkyKid_Neck_AP01Pendant",
    "CharSkyKid_Neck_AP06Pendant",
    "CharSkyKid_Neck_AP07Pendant",
    "CharSkyKid_Neck_AP08Pendant",
    "CharSkyKid_Neck_AP09Pendant",
    "CharSkyKid_Neck_AP10Pendant",
    "CharSkyKid_Neck_AP11Pendant",
    "CharSkyKid_Neck_AP12Pendant",
    "CharSkyKid_Neck_AP13Pendant",
    "CharSkyKid_Neck_AP14Pendant",
    "CharSkyKid_Neck_AP15Pendant",
    "CharSkyKid_Neck_AP16Pendant",
    "CharSkyKid_Neck_AP17Pendant",
    "CharSkyKid_Neck_AP18Pendant",
    "CharSkyKid_Neck_AP19Pendant",
    "CharSkyKid_Neck_AP20Pendant",
    "CharSkyKid_Neck_AP21Pendant",
    "CharSkyKid_Neck_AP22Pendant",
    "CharSkyKid_Neck_AP23Pendant",
    "CharSkyKid_Neck_AP24Pendant",
    "CharSkyKid_Neck_AP25Pendant",
    "CharSkyKid_Neck_AP26Pendant",
    "CharSkyKid_Neck_AP27Pendant",
    "CharSkyKid_Neck_AP28Pendant",
    "CharSkyKid_Neck_AP29Pendant",
    "CharSkyKid_Neck_AP07BowTie",
    "CharSkyKid_Neck_AP11Ascot_01",
    "CharSkyKid_Neck_AP12Scales_01",
    "CharSkyKid_Neck_AP15Crab_01",
    "CharSkyKid_Neck_AP17Scarf",
    "CharSkyKid_Neck_AP17Sash",
    "CharSkyKid_Neck_AP18FluffyRuff",
    "CharSkyKid_Neck_AP24Bell",
    "CharSkyKid_Neck_AP24Arms",
    "CharSkyKid_Neck_AP24OnionRibbon",
    "CharSkyKid_Neck_AP24TriangleScarf",
    "CharSkyKid_Neck_AP24StripesScarf",
    "CharSkyKid_Neck_DragonBodyBlack",
    "CharSkyKid_Neck_DragonHeadBlack",
    "CharSkyKid_Neck_DragonTailBlack",
    "CharSkyKid_Neck_DragonBodyWhite",
    "CharSkyKid_Neck_DragonHeadWhite",
    "CharSkyKid_Neck_DragonTailWhite",
    "CharSkyKid_Neck_Bow",
    "CharSkyKid_Neck_Ocean_01",
    "CharSkyKid_Neck_SeaTurtle_01",
    "CharSkyKid_Neck_ShoulderButterfly",
    "CharSkyKid_Neck_OceanScarf",
    "CharSkyKid_Neck_RibbonBib",
    "CharSkyKid_Neck_Jellyfish_01",
    "CharSkyKid_Neck_KrillTie",
    "CharSkyKid_Neck_Xmas",
    "CharSkyKid_Neck_WinterScarf_01",
    "CharSkyKid_Neck_WinterScarfBlue",
    "CharSkyKid_Neck_MedalGold",
    "CharSkyKid_Neck_MedalSilver",
    "CharSkyKid_Neck_MedalBronze",
    "CharSkyKid_Neck_PastryBow",
    "CharSkyKid_Neck_CrabBandana",
    "CharSkyKid_Neck_WinterScarf_Ghost",
    "CharSkyKid_Neck_Crab",
    "CharSkyKid_Neck_CrabBow",
    "NPC_SkinnyIntellectualShawlUp",
    "CharSkyKid_Tail_AP24Classic",
    "CharSkyKid_Tail_AP27KrillTail",
    "CharSkyKid_Tail_AP27ManateeTail",
    "CharSkyKid_Tail_MischiefCat",
    "CharSkyKid_Tail_MoonlightRabbit",
    "Nest_MainStreetApartment_Capacity_1",
    "Nest_MainStreetApartment_Capacity_2",
    "Nest_MainStreetApartment_Capacity_3",
    "CharSkyKid_Neck_AP30RuffledCollar",
    "CharSkyKid_Neck_AP30Pendant",
};
static_assert(sizeof(kNeckOutfitValues) / sizeof(kNeckOutfitValues[0]) == 77,
              "feature 1504 neck table size mismatch");

constexpr const char *kHairOutfitValues[] = {
    "CharSkyKid_Hair_BraidSideSmall",
    "CharSkyKid_Hair_TightCurls",
    "CharSkyKid_Hair_PigtailLow",
    "CharSkyKid_Hair_BraidSide",
    "CharSkyKid_Hair_BraidBack",
    "CharSkyKid_Hair_PonytailShort",
    "CharSkyKid_Hair_PonytailShaggy",
    "CharSkyKid_Hair_ShaggyShort",
    "CharSkyKid_Hair_BraidTwo",
    "CharSkyKid_Hair_TopTwoKnot",
    "CharSkyKid_Hair_TopTwoKnotBig",
    "CharSkyKid_Hair_Bun",
    "CharSkyKid_Hair_Buzz",
    "CharSkyKid_Hair_TopSharp",
    "CharSkyKid_Hair_Mohawk",
    "CharSkyKid_Hair_ShoulderLong",
    "CharSkyKid_Hair_TwoTails",
    "CharSkyKid_Hair_ShortBob",
    "CharSkyKid_Hair_ShortBobRound",
    "CharSkyKid_Hair_LongBob",
    "CharSkyKid_Hair_PunkTall",
    "CharSkyKid_Hair_TopOneSideS",
    "CharSkyKid_Hair_TopOneSideM",
    "CharSkyKid_Hair_TopOneSideL",
    "CharSkyKid_Hair_Dreads",
    "CharSkyKid_Hair_BackLong",
    "CharSkyKid_Hair_Beard",
    "CharSkyKid_Hair_ShoulderLongTie",
    "CharSkyKid_Hair_Lion",
    "CharSkyKid_Hair_Puff",
    "CharSkyKid_Hair_Afro",
    "CharSkyKid_Hair_BallCurly",
    "CharSkyKid_Hair_TwoBallsCurly",
    "CharSkyKid_Hair_ElderDawn",
    "CharSkyKid_Hair_ElderDay",
    "CharSkyKid_Hair_ElderRain",
    "CharSkyKid_Hair_ElderBro",
    "CharSkyKid_Hair_ElderSis",
    "CharSkyKid_Hair_ElderDusk",
    "CharSkyKid_Hair_ElderNight",
    "CharSkyKid_Hair_AP02Stupa_01",
    "CharSkyKid_Hair_AP02Bhutan_01",
    "CharSkyKid_Hair_AP02Cone_01",
    "CharSkyKid_Hair_AP03Victorian_01",
    "CharSkyKid_Hair_AP03Samurai_01",
    "CharSkyKid_Hair_AP03Barrette_01",
    "CharSkyKid_Hair_AP03Upstyle_01",
    "CharSkyKid_Hair_AP03Umbrella_01",
    "CharSkyKid_Hair_AP04Ribbon_01",
    "CharSkyKid_Hair_AP04WavyBob_01",
    "CharSkyKid_Hair_APDancer_01",
    "CharSkyKid_Hair_APJuggler_01",
    "CharSkyKid_Hair_APMusician_01",
    "CharSkyKid_Hair_AP05Director_01",
    "CharSkyKid_Hair_AP06ConeHat_01",
    "CharSkyKid_Hair_AP06WizardHat_01",
    "CharSkyKid_Hair_AP06BunRound_01",
    "CharSkyKid_Hair_AP06ScoutHat_01",
    "CharSkyKid_Hair_AP06WizardHair_01",
    "CharSkyKid_Hair_AP06Pigtails_01",
    "CharSkyKid_Hair_AP06Turban_01",
    "CharSkyKid_Hair_AP07Jellyfish_01",
    "CharSkyKid_Hair_AP07Braid_01",
    "CharSkyKid_Hair_AP07Undercut_01",
    "CharSkyKid_Hair_AP07Balding_01",
    "CharSkyKid_Hair_AP07BowlCut_01",
    "CharSkyKid_Hair_AP08Ponytail_01",
    "CharSkyKid_Hair_AP08DoubleBun_01",
    "CharSkyKid_Hair_AP08Braid_01",
    "CharSkyKid_Hair_AP08ShortDreads_01",
    "CharSkyKid_Hair_AP09Yeti_01",
    "CharSkyKid_Hair_AP09Hat_01",
    "CharSkyKid_Hair_AP09MultiBuns_01",
    "CharSkyKid_Hair_AP09BambooHat_01",
    "CharSkyKid_Hair_AP10PotHat_01",
    "CharSkyKid_Hair_AP10StrawCrown_01",
    "CharSkyKid_Hair_AP10PonytailDreads_01",
    "CharSkyKid_Hair_AP10LongBangs_01",
    "CharSkyKid_Hair_AP10FrontBraids_01",
    "CharSkyKid_Hair_AP10Bandana_01",
    "CharSkyKid_Hair_AP11Messy_01",
    "CharSkyKid_Hair_AP11LongWavy_01",
    "CharSkyKid_Hair_AP11UniformHat_01",
    "CharSkyKid_Hair_AP11Crown_01",
    "CharSkyKid_Hair_AP11ConeHat_01",
    "CharSkyKid_Hair_AP11Prince_01",
    "CharSkyKid_Hair_AP12FeatherHat_01",
    "CharSkyKid_Hair_AP12RuffledLong_01",
    "CharSkyKid_Hair_AP12RuffledShort_01",
    "CharSkyKid_Hair_AP12Goggles_01",
    "CharSkyKid_Hair_AP13LongBraids_01",
    "CharSkyKid_Hair_AP13TattooBraids_01",
    "CharSkyKid_Hair_AP13BucketHat_01",
    "CharSkyKid_Hair_AP14TuftedDirector_01",
    "CharSkyKid_Hair_AP14HeadWrap_01",
    "CharSkyKid_Hair_AP14ShadowHood_01",
    "CharSkyKid_Hair_AP14JesterHood_01",
    "CharSkyKid_Hair_AP14CurlyLong_01",
    "CharSkyKid_Hair_AP15Krill_01",
    "CharSkyKid_Hair_AP15Manta_01",
    "CharSkyKid_Hair_AP15Jellyfish_01",
    "CharSkyKid_Hair_AP16Fire",
    "CharSkyKid_Hair_AP16Water",
    "CharSkyKid_Hair_AP16Wind",
    "CharSkyKid_Hair_AP16Earth",
    "CharSkyKid_Hair_AP16RunawayBob",
    "CharSkyKid_Hair_AP16ClassicAurora",
    "CharSkyKid_Hair_AP17PaperboyCap",
    "CharSkyKid_Hair_AP17Genius",
    "CharSkyKid_Hair_AP17BandanaBraid",
    "CharSkyKid_Hair_AP18Spiky",
    "CharSkyKid_Hair_AP18MediumBob",
    "CharSkyKid_Hair_AP18SlickBack",
    "CharSkyKid_Hair_AP18SideFade",
    "CharSkyKid_Hair_AP19DoubleBraidBack",
    "CharSkyKid_Hair_AP19HeadTattoo",
    "CharSkyKid_Hair_AP19Skull",
    "CharSkyKid_Hair_AP20SlickBowlCut",
    "CharSkyKid_Hair_AP20Beads",
    "CharSkyKid_Hair_AP20Maypole",
    "CharSkyKid_Hair_AP20MaypoleNoRibbons",
    "CharSkyKid_Hair_AP21FancyUpdo",
    "CharSkyKid_Hair_AP21Turban",
    "CharSkyKid_Hair_AP21RoyalBun",
    "CharSkyKid_Hair_AP21HunterBun",
    "CharSkyKid_Hair_AP22Pigtail",
    "CharSkyKid_Hair_AP23PianistKnot",
    "CharSkyKid_Hair_AP23CellistBun",
    "CharSkyKid_Hair_AP24Onion",
    "CharSkyKid_Hair_AP24Triangle",
    "CharSkyKid_Hair_AP25BluePaint",
    "CharSkyKid_Hair_AP25Bob",
    "CharSkyKid_Hair_AP26LowHat",
    "CharSkyKid_Hair_AP27HelmetPlumed",
    "CharSkyKid_Hair_AP27HelmetScarred",
    "CharSkyKid_Hair_AP27CaretakerHood",
    "CharSkyKid_Hair_AP27FluffyManatee",
    "CharSkyKid_Hair_AP28MantaWhisperer",
    "CharSkyKid_Hair_AP28Father",
    "CharSkyKid_Hair_AP29Highlights",
    "CharSkyKid_Hair_AP29LongHood",
    "CharSkyKid_Hair_AP29KnotBun",
    "CharSkyKid_Hair_DoubleBun",
    "CharSkyKid_Hair_WoolHat",
    "CharSkyKid_Hair_LionDance",
    "CharSkyKid_Hair_Fish_01",
    "CharSkyKid_Hair_FortuneSnake",
    "CharSkyKid_Hair_Blossom_01",
    "CharSkyKid_Hair_CallaLily",
    "CharSkyKid_Hair_BloomSpiky",
    "CharSkyKid_Hair_RoseBraid",
    "CharSkyKid_Hair_BloomSunflowerBandana",
    "CharSkyKid_Hair_NatureWater",
    "CharSkyKid_Hair_ElderManta",
    "CharSkyKid_Hair_RainbowHat_01",
    "CharSkyKid_Hair_RockStar",
    "CharSkyKid_Hair_ColorHeadband",
    "CharSkyKid_Hair_MarchingBand",
    "CharSkyKid_Hair_MoonlightUpdo",
    "CharSkyKid_Hair_AP04Pumpkin_01",
    "CharSkyKid_Hair_WitchHat_01",
    "CharSkyKid_Hair_MischiefCat",
    "CharSkyKid_Hair_Witch",
    "CharSkyKid_Hair_Spider_01",
    "CharSkyKid_Hair_SpiderBun",
    "CharSkyKid_Hair_MischiefFeatherHat",
    "CharSkyKid_Hair_MischiefSmoked",
    "CharSkyKid_Hair_Xmas",
    "CharSkyKid_Hair_WinterHat_01",
    "CharSkyKid_Hair_Snowman",
    "CharSkyKid_Hair_Frantic",
    "CharSkyKid_Hair_BlueHare",
    "CharSkyKid_Hair_MeteorPigtails",
    "CharSkyKid_Hair_PurpleBraids",
    "CharSkyKid_Hair_PastryShort",
    "CharSkyKid_Hair_Greek",
    "CharSkyKid_Hair_TriumphSwept",
    "CharSkyKid_Hair_FortunePonytail",
    "CharSkyKid_Hair_TreasureBandanaLong",
    "CharSkyKid_Hair_KizunaAi_Red",
    "CharSkyKid_Hair_KizunaAi_Pink",
    "CharSkyKid_Hair_Elf_01",
    "CharSkyKid_Hair_Traveler_01",
    "CharSkyKid_Hair_Traveler_02",
    "CharSkyKid_Hair_None",
    "NPC_AP29HighlightsHair",
    "CharSkyNPC_Hair_FatLaborBun",
    "CharSkyKid_Hair_AP30TaperDirector",
    "CharSkyKid_Hair_AP30HighPonytail",
    "CharSkyKid_Hair_AP30AviatorHat",
};
static_assert(sizeof(kHairOutfitValues) / sizeof(kHairOutfitValues[0]) == 190,
              "feature 1505 hair table size mismatch");

constexpr const char *kHornOutfitValues[] = {
    "CharSkyKid_Horn_None",
    "CharSkyKid_Horn_TuneBand",
    "CharSkyKid_Horn_AP04EarMuffs",
    "CharSkyKid_Horn_AP06Tassel",
    "CharSkyKid_Horn_AP09Yeti_01",
    "CharSkyKid_Horn_AP13Braids_01",
    "CharSkyKid_Horn_AP16MoonStar",
    "CharSkyKid_Horn_AP18Tusk",
    "CharSkyKid_Horn_AP18FabricStrip",
    "CharSkyKid_Horn_AP21Deer",
    "CharSkyKid_Horn_AP25YellowPaint",
    "CharSkyKid_Horn_AP26EarMuff",
    "CharSkyKid_Horn_AP27KrillHorns",
    "CharSkyKid_Horn_AP27ManateeFins",
    "CharSkyKid_Horn_AP29OrbEarring",
    "CharSkyKid_Horn_DragonEarring",
    "CharSkyKid_Horn_RainbowTassel_01",
    "CharSkyKid_Horn_RainbowEarring_01",
    "CharSkyKid_Horn_RainbowHeadphones_01",
    "CharSkyKid_Horn_DarkRainbowEarring",
    "CharSkyKid_Horn_SunnyEarring",
    "CharSkyKid_Horn_MoonEarring",
    "CharSkyKid_Horn_Withered_01",
    "CharSkyKid_Horn_Elk",
    "CharSkyKid_Horn_BloomSunflowerEarring",
    "CharSkyKid_Horn_FireworkEarring",
    "CharSkyNPC_Horn_SkinnyIntellectualCrown",
    "CharSkyNPC_Horn_FatLaborChains",
    "CharSkyNPC_Horn_FatLaborChains_02",
    "CharSkyNPC_Horn_MCivilianChains",
    "CharSkyNPC_Horn_SkinnyIntellectualChains",
    "CharSkyNPC_Horn_StrongLaborChains",
};
static_assert(sizeof(kHornOutfitValues) / sizeof(kHornOutfitValues[0]) == 32,
              "feature 1507 horn table size mismatch");

constexpr const char *kWingOutfitValues[] = {
    "CharSkyKid_Wing_ClassicOne_Default",
    "CharSkyKid_Wing_ClassicOne_TGCBlue",
    "CharSkyKid_Wing_ClassicOne_TGCBlue$",
    "CharSkyKid_Wing_ClassicOne_TGCBlueSTAR",
    "CharSkyKid_Wing_ClassicOne_Orange",
    "CharSkyKid_Wing_ClassicOne_Yellow",
    "CharSkyKid_Wing_ClassicOne_Red",
    "CharSkyKid_Wing_ClassicOne_Beige",
    "CharSkyKid_Wing_ClassicOne_Teal",
    "CharSkyKid_Wing_ClassicOne_Ancestor",
    "CharSkyKid_Wing_ClassicOne_Purple",
    "CharSkyKid_Wing_ClassicOne_Pink",
    "CharSkyKid_Wing_ClassicOne_Black",
    "CharSkyKid_Wing_ClassicOne_White",
    "CharSkyKid_Wing_ClassicTwo_Default",
    "CharSkyKid_Wing_ClassicTwo_Orange",
    "CharSkyKid_Wing_ClassicTwo_Yellow",
    "CharSkyKid_Wing_ClassicTwo_Red",
    "CharSkyKid_Wing_ClassicTwo_Beige",
    "CharSkyKid_Wing_ClassicTwo_Teal",
    "CharSkyKid_Wing_ClassicTwo_Ancestor",
    "CharSkyKid_Wing_ClassicTwo_Purple",
    "CharSkyKid_Wing_ClassicTwo_Pink",
    "CharSkyKid_Wing_ClassicTwo_Black",
    "CharSkyKid_Wing_ClassicTwo_White",
    "CharSkyKid_Wing_ClassicRey",
    "CharSkyKid_Wing_ClassicDiamonds",
    "CharSkyKid_Wing_AP02Fur_01",
    "CharSkyKid_Wing_AP02Tail_01",
    "CharSkyKid_Wing_AP03Petal_01",
    "CharSkyKid_Wing_AP03Biolum_01",
    "CharSkyKid_Wing_AP03Biolum_02",
    "CharSkyKid_Wing_AP04Child_01",
    "CharSkyKid_Wing_AP04Adult_01",
    "CharSkyKid_Wing_AP04Elder_01",
    "CharSkyKid_Wing_APJuggler_01",
    "CharSkyKid_Wing_APDirector_01",
    "CharSkyKid_Wing_AP06Trim_01",
    "CharSkyKid_Wing_AP06Tassel_02",
    "CharSkyKid_Wing_AP06Layered_01",
    "CharSkyKid_Wing_AP06Layered_02",
    "CharSkyKid_Wing_AP07Butterfly_01",
    "CharSkyKid_Wing_AP07Manta_01",
    "CharSkyKid_Wing_AP07Shell_01",
    "CharSkyKid_Wing_AP07Aloha_01",
    "CharSkyKid_Wing_AP08Bat_01",
    "CharSkyKid_Wing_AP08Turtle_01",
    "CharSkyKid_Wing_AP08Spider_01",
    "CharSkyKid_Wing_AP09Waves_01",
    "CharSkyKid_Wing_AP09Robe_01",
    "CharSkyKid_Wing_AP09Fur_01",
    "CharSkyKid_Wing_AP09Phoenix_01",
    "CharSkyKid_Wing_AP10YellowCape_01",
    "CharSkyKid_Wing_AP10GreenCape_01",
    "CharSkyKid_Wing_AP11HeavyFur_01",
    "CharSkyKid_Wing_AP11Tattered_01",
    "CharSkyKid_Wing_AP11Uniform_01",
    "CharSkyKid_Wing_AP11Wrinkled_01",
    "CharSkyKid_Wing_AP11Scarf_01",
    "CharSkyKid_Wing_AP11GreenCoat_01",
    "CharSkyKid_Wing_AP12BlueWing_01",
    "CharSkyKid_Wing_AP12TwoTone_01",
    "CharSkyKid_Wing_AP13LeatherScales_01",
    "CharSkyKid_Wing_AP13Shoulder_01",
    "CharSkyKid_Wing_AP13Shawl_01",
    "CharSkyKid_Wing_AP13Coat_01",
    "CharSkyKid_Wing_AP13NobleCloak_01",
    "CharSkyKid_Wing_AP14Tuxedo_01",
    "CharSkyKid_Wing_AP14Jester_01",
    "CharSkyKid_Wing_AP14TatteredScarf_01",
    "CharSkyKid_Wing_AP15DarkPlant_01",
    "CharSkyKid_Wing_AP15Krill_01",
    "CharSkyKid_Wing_AP15Jellyfish_01",
    "CharSkyKid_Wing_AP15BabyManta_01",
    "CharSkyKid_Wing_AP15BigManta_01",
    "CharSkyKid_Wing_AP16Fire",
    "CharSkyKid_Wing_AP16Water",
    "CharSkyKid_Wing_AP16Wind",
    "CharSkyKid_Wing_AP16Earth",
    "CharSkyKid_Wing_AP16ButterflyYellow",
    "CharSkyKid_Wing_AP16ButterflyBlue",
    "CharSkyKid_Wing_AP16OrangeLove",
    "CharSkyKid_Wing_AP17UniformCloak",
    "CharSkyKid_Wing_AP17InjuredSoldier",
    "CharSkyKid_Wing_AP17TiedShawl",
    "CharSkyKid_Wing_AP18RaccoonTail",
    "CharSkyKid_Wing_AP18FauxPelt",
    "CharSkyKid_Wing_AP18FurryGuard",
    "CharSkyKid_Wing_AP19Poncho",
    "CharSkyKid_Wing_AP20Rhythm",
    "CharSkyKid_Wing_AP20Gratitude",
    "CharSkyKid_Wing_AP20Enchantment",
    "CharSkyKid_Wing_AP20Abyss",
    "CharSkyKid_Wing_AP20MaypoleScarf",
    "CharSkyKid_Wing_AP21SilkSash",
    "CharSkyKid_Wing_AP21SilkShawl",
    "CharSkyKid_Wing_AP21LinenScarf",
    "CharSkyKid_Wing_AP21KingCloak",
    "CharSkyKid_Wing_AP21Deer",
    "CharSkyKid_Wing_AP22Designer",
    "CharSkyKid_Wing_AP23PianistCloak",
    "CharSkyKid_Wing_AP23CellistCloak",
    "CharSkyKid_Wing_AP24Bell",
    "CharSkyKid_Wing_AP24Triangle",
    "CharSkyKid_Wing_AP24Arms",
    "CharSkyKid_Wing_AP25Detached",
    "CharSkyKid_Wing_AP25Ribbons",
    "CharSkyKid_Wing_AP25DyeCloth",
    "CharSkyKid_Wing_AP26Heuke",
    "CharSkyKid_Wing_AP26Hourglass",
    "CharSkyKid_Wing_AP26MoonCloak",
    "CharSkyKid_Wing_AP26BlueBird",
    "CharSkyKid_Wing_AP27GuardCape",
    "CharSkyKid_Wing_AP27Darkness",
    "CharSkyKid_Wing_AP27NightElder",
    "CharSkyKid_Wing_AP28CharmerCape",
    "CharSkyKid_Wing_AP28BirdWhisperer",
    "CharSkyKid_Wing_AP28GuardianCape",
    "CharSkyKid_Wing_AP28MantaWhisperer",
    "CharSkyKid_Wing_AP29LightStrands",
    "CharSkyKid_Wing_AP29DoubleFive",
    "CharSkyKid_Wing_AP29Shush",
    "CharSkyKid_Wing_Fortune",
    "CharSkyKid_Wing_Fish_01",
    "CharSkyKid_Wing_FortuneDragon",
    "CharSkyKid_Wing_FortuneSnake",
    "CharSkyKid_Wing_Blossom_01",
    "CharSkyKid_Wing_Wisteria_01",
    "CharSkyKid_Wing_Tulip",
    "CharSkyKid_Wing_CallaLily",
    "CharSkyKid_Wing_RosePattern",
    "CharSkyKid_Wing_BloomSunflower",
    "CharSkyKid_Wing_ClassicOne_EarthDay",
    "CharSkyKid_Wing_Ocean_01",
    "CharSkyKid_Wing_SeaTurtle_01",
    "CharSkyKid_Wing_SeaFoam",
    "CharSkyKid_Wing_FishPattern",
    "CharSkyKid_Wing_WaterWave",
    "CharSkyKid_Wing_Rainbow_01",
    "CharSkyKid_Wing_DarkRainbow",
    "CharSkyKid_Wing_ColorShawl",
    "CharSkyKid_Wing_TGCHoodie",
    "CharSkyKid_Wing_TGCWireframe",
    "CharSkyKid_Wing_TGCWireframeEvergreen",
    "CharSkyKid_Wing_TeamDusk",
    "CharSkyKid_Wing_TeamPrairie",
    "CharSkyKid_Wing_TeamSunset",
    "CharSkyKid_Wing_TeamRain",
    "CharSkyKid_Wing_SunlightTowelBlue",
    "CharSkyKid_Wing_SunlightTowelPink",
    "CharSkyKid_Wing_SunlightTowelYellow",
    "CharSkyKid_Wing_SunlightShawl",
    "CharSkyKid_Wing_LinenCover",
    "CharSkyKid_Wing_Moonlight",
    "CharSkyKid_Wing_Bat",
    "CharSkyKid_Wing_ClassicOne_TGCBlueBat",
    "CharSkyKid_Wing_SpiderWeb_01",
    "CharSkyKid_Wing_Withered_01",
    "CharSkyKid_Wing_MischiefCat",
    "CharSkyKid_Wing_MischiefGoth",
    "CharSkyKid_Wing_ClassicOne_Crab",
    "CharSkyKid_Wing_Cobweb",
    "CharSkyKid_Wing_Crabula",
    "CharSkyKid_Wing_Raven",
    "CharSkyKid_Wing_Xmas",
    "CharSkyKid_Wing_Snowflake",
    "CharSkyKid_Wing_WinterElder_01",
    "CharSkyKid_Wing_YetiFur",
    "CharSkyKid_Wing_WinterPuffer",
    "CharSkyKid_Wing_FeastFluffyShawl",
    "CharSkyKid_Wing_FeastScarf",
    "CharSkyKid_Wing_Meteor",
    "CharSkyKid_Wing_PastryCloud",
    "CharSkyKid_Wing_BandJacket",
    "CharSkyKid_Wing_AnnivTuxedo",
    "CharSkyKid_Wing_RibbonDressCape",
    "CharSkyKid_Wing_RibbonBow",
    "CharSkyKid_Wing_TriumphIce",
    "CharSkyKid_Wing_FortuneHorse",
    "CharSkyKid_Wing_Sparrow",
    "CharSkyKid_Wing_Moth",
    "CharSkyKid_Wing_KizunaAi_Pink",
    "CharSkyKid_Wing_KizunaAi_Red",
    "CharSkyKid_Wing_SwitchRed_01",
    "CharSkyKid_Wing_SwitchBlue_01",
    "CharSkyKid_Wing_Traveler_01",
    "CharSkyKid_Wing_Traveler_02",
    "CharSkyKid_Wing_Flow",
    "CharSkyKid_Wing_None",
    "CharSkyKid_Wing_MaskRampEffects",
    "NPC_CivilianMaleShoulder",
    "NPC_CivilianFemaleShoulder",
    "NPC_LaborerMaleShoulder",
    "NPC_LaborerMaleHeadwrap",
    "NPC_AP21KingCloak",
    "NPC_AP25DyeCloth",
    "NPC_AP29LightStrandsWing",
    "CharSkyNPC_Wing_AP28CharmerCape",
    "CharSkyKid_Wing_AP30Curly",
    "CharSkyKid_Wing_AP30LongCoat",
    "CharSkyKid_Wing_AP30SpiritBird",
    "CharSkyKid_Wing_TreasureCoin",
};
static_assert(sizeof(kWingOutfitValues) / sizeof(kWingOutfitValues[0]) == 202,
              "feature 1508 wing table size mismatch");

constexpr OutfitSlotTable kOutfitSlotTables[] = {
    {1501, "body", kBodyOutfitValues, sizeof(kBodyOutfitValues) / sizeof(kBodyOutfitValues[0])},
    {1502, "mask", kMaskOutfitValues, sizeof(kMaskOutfitValues) / sizeof(kMaskOutfitValues[0])},
    {1503, "face", kFaceOutfitValues, sizeof(kFaceOutfitValues) / sizeof(kFaceOutfitValues[0])},
    {1504, "neck", kNeckOutfitValues, sizeof(kNeckOutfitValues) / sizeof(kNeckOutfitValues[0])},
    {1505, "hair", kHairOutfitValues, sizeof(kHairOutfitValues) / sizeof(kHairOutfitValues[0])},
    {1507, "horn", kHornOutfitValues, sizeof(kHornOutfitValues) / sizeof(kHornOutfitValues[0])},
    {1508, "wing", kWingOutfitValues, sizeof(kWingOutfitValues) / sizeof(kWingOutfitValues[0])},
};

const OutfitSlotTable *tableForFeature(int feature_num) {
    for (const OutfitSlotTable &table : kOutfitSlotTables) {
        if (table.feature_num == feature_num) {
            return &table;
        }
    }
    return nullptr;
}

} // namespace

const char *outfitSlotMethodForFeature(int feature_num) {
    const OutfitSlotTable *table = tableForFeature(feature_num);
    return table ? table->method : nullptr;
}

bool isAvatarSetOutfitSlotFeature(int feature_num) {
    return tableForFeature(feature_num) != nullptr;
}

std::string outfitSlotValueForFeatureItem(int feature_num, int item_id) {
    const OutfitSlotTable *table = tableForFeature(feature_num);
    if (table == nullptr || item_id <= 0 || item_id > static_cast<int>(table->count)) {
        return {};
    }
    return table->values[item_id - 1];
}

bool sendAvatarSetOutfitSlotCommand(const char *method, const std::string &value) {
    if (method == nullptr || method[0] == '\0' || value.empty()) {
        return false;
    }

    std::string command =
        "local e=game:eventBarn():AddEventByMetaName('AvatarSetOutfit') "
        "if e then e:";
    command += method;
    command += "('";
    command += value;
    command += "') e:playAnim(true) e:Start(0) end";
    return sendGameCommand(command);
}

bool sendAvatarSetOutfitFeatureCommand(int feature_num, int item_id) {
    const OutfitSlotTable *table = tableForFeature(feature_num);
    if (table == nullptr) {
        return false;
    }

    std::string value = outfitSlotValueForFeatureItem(feature_num, item_id);
    if (value.empty()) {
        logWarn("AvatarSetOutfit %s unknown item_id=%d", table->method, item_id);
        return false;
    }

    return sendAvatarSetOutfitSlotCommand(table->method, value);
}

}
